import {
  User,
  Mail,
  Phone,
  CreditCard,
  MessageCircle,
  MapPin,
  DollarSign,
  Calendar,
} from "lucide-react";

export const fields = [
  {
    id: "name",
    label: "Nome",
    type: "text",
    icon: User,
    required: true,
    placeholder: "Seu nome completo",
  },
  {
    id: "cpf",
    label: "CPF",
    type: "text",
    inputMode: "numeric",
    maxLength: 14,
    placeholder: "000.000.000-00",
    icon: CreditCard,
    required: true,
  },
  {
    id: "phone",
    label: "Whatsapp para resposta (com DDD)",
    type: "tel",
    inputMode: "numeric",
    maxLength: 15,
    icon: Phone,
    required: true,
    placeholder: "(18) 99999-9999",
  },
  {
    id: "email",
    label: "E-mail",
    type: "email",
    icon: Mail,
    required: true,
    placeholder: "voce@email.com",
  },
  {
    id: "modalidade",
    label: "Qual tipo de financiamento você deseja?",
    type: "select",
    icon: MessageCircle,
    required: true,
    options: [
      "Aquisição de Imóvel Usado",
      "Aquisição de Imóvel Novo",
      "Construção em Terreno Próprio",
      "Aquisição de Terreno e Construção",
      "Reforma",
      "Ampliação",
      "Outro",
    ],
  },
  {
    id: "modalidadeOutro",
    label: "Digite a modalidade",
    type: "text",
    icon: MessageCircle,
    required: false,
    placeholder: "Ex: Financiamento de energia solar",
    dependsOn: { field: "modalidade", value: "Outro" },
  },
  {
    id: "cidade",
    label: "Em qual Cidade está Localizado o Imóvel?",
    type: "text",
    icon: MapPin,
    required: true,
    placeholder: "Digite a Cidade",
  },
  {
    id: "renda",
    label: "Qual é a renda bruta familiar?",
    type: "text",
    inputMode: "numeric",
    icon: DollarSign,
    required: true,
    placeholder: "R$ 0,00",
  },
  {
    id: "possuiFgts",
    label:
      "Possui 3 anos de trabalho sob regime do FGTS, somando-se todos os períodos trabalhados?",
    type: "radio",
    required: true,
    options: ["Sim", "Não"],
  },
  {
    id: "nascimento",
    label:
      "Qual é a data de nascimento do participante de maior idade? (Ex: 15/08/1990)",
    type: "text",
    inputMode: "numeric",
    maxLength: 10,
    icon: Calendar,
    required: true,
    placeholder: "DD/MM/AAAA",
  },
  {
    id: "possuiDependente",
    label: "Possui mais de um comprador e/ou dependente na proposta?",
    type: "radio",
    required: true,
    options: ["Sim", "Não"],
  },
  {
    id: "possuiImovel",
    label: "Possui imóvel reigstrado em seu nome?",
    type: "radio",
    required: true,
    options: ["Sim", "Não"],
  },
  {
    id: "cidadeImovelNoNome",
    label: "Caso Possua imóvel, é em qual Cidade?",
    type: "text",
    icon: MapPin,
    required: false,
    placeholder: "Digite a Cidade",
  },
  {
    id: "recursosProprios",
    label:
      "Qual o Valor de Recursos Próprios para a Entrada? Sem Somar FGTS em caso de uso. ",
    type: "text",
    inputMode: "numeric",
    icon: DollarSign,
    required: true,
    placeholder: "R$ 0,00",
  },
  {
    id: "valorFGTS",
    label: "Pretende utilizar FGTS? Se sim, qual valor?",
    type: "text",
    inputMode: "numeric",
    icon: DollarSign,
    required: true,
    placeholder: "R$ 0,00",
  },
];

export function isFieldActive(field, values) {
  if (!field.dependsOn) return true;
  return values[field.dependsOn.field] === field.dependsOn.value;
}
